### PR TITLE
a large amount of new claims courtesy of lowtuff

### PR DESCRIPTION
**Pull request by MrJoCrafter**
let's see if this works

### CODE REVIEW

**Comment by Gjum** [comment]
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 70 column 1 (char 3235)

**Comment by MrJoCrafter** [comment]
the error was on line 69 but it threw an error for 70

**Comment by MrJoCrafter** [comment]
okay it is FINALLY done

**Comment by MrJoCrafter** [comment]
@Gjum this should be good now right

**Comment by MrJoCrafter** [comment]
@Gjum i literally cannot find the error. it's throwing an inaccurate error again

**Comment by Gjum** [comment]
`{"name":"Dankia",...,"declutter":3,,"polygon":[`
notice the two commas ;)

**Comment by MrJoCrafter** [comment]
okay @Gjum it's finally finished and clean

**Review by Gjum — APPROVED** [review]

**Pull request merged**
