### PR TITLE
Make it so it auto updates the list of nations by area automatically

### PR DESCRIPTION
**Pull request by Metriximor**
It's been tested, not sure if the secrets will also transfer but if it won't I'll look at it

### CODE REVIEW

**Comment by Metriximor** [comment]
@Gjum you need to setup the github secrets cause I don't have a permission to do so, lmk and I'll send you the username and password

**Comment by Gjum** [comment]
@Metriximor can you mail them to me on gmail (minecraft.gjum@), and I'll put them ... [here I guess?](https://docs.github.com/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)

**Comment by Metriximor** [comment]
@Gjum ok I sent you an email from civwikibot@gmail with details of how to setup the secrets and the secrets themselves

**Comment by Gjum** [comment]
@Metriximor I think I've added them in the right place, let's see if this works

**Comment by Metriximor** [comment]
@Gjum happy to report I just ran it manually(you can do it by going to actions and selecting the run workflow button) and it worked beautifully(it should also run automatically whenever a change happens on the appropriate file, thus keeping the civwiki updated automatically with ccmap/data)
image

**Comment by Gjum** [comment]
That's amazing, nice work!

**Pull request merged**
