### PR TITLE
Update Ashelor's settlements

### PR DESCRIPTION
**Pull request by Protonull**

### CODE REVIEW

**Comment by Gjum** [comment]
can you retain the previous nations like this `Ashelor, formerly Maltovia, formerly Dithmarschen` etc

**Comment by Protonull** [comment]
They're all part of Ashelor now

**Comment by Gjum** [comment]
Yes. CCMap displays the names of previous groups that contributed to each area. Maybe that's dumb, suggestions welcome.

**Comment by Protonull** [comment]
It'd be cool to have a way to show bullet points, that way I can show the history of these settlements more easily. Part of the problem I have with "`Ashelor, formerly Maltovia, formerly Dithmarschen`" is that it also implies that Ashelor itself was formally [part of] Maltovia and Dithmarschen, rather than just the settlements / the territory.

**Pull request merged**
